"""initial schema

Revision ID: 85f1cd1ec781
Revises: 
Create Date: 2026-06-08 07:58:22.691704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85f1cd1ec781'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('external_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validation_error', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_integrations_user_id'), 'external_integrations', ['user_id'], unique=False)
    op.create_table('notion_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('workspace_name', sa.Text(), nullable=True),
    sa.Column('workspace_icon', sa.Text(), nullable=True),
    sa.Column('bot_id', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notion_integrations_user_id'), 'notion_integrations', ['user_id'], unique=False)
    op.create_index(op.f('ix_notion_integrations_workspace_id'), 'notion_integrations', ['workspace_id'], unique=True)
    op.create_table('sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('external_integration_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_integration_id'], ['external_integrations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_external_integration_id'), 'sync_runs', ['external_integration_id'], unique=False)
    op.create_index('ix_sync_runs_failed_pending', 'sync_runs', ['status', 'started_at'], unique=False, postgresql_where="status IN ('failed', 'pending')")
    op.create_index(op.f('ix_sync_runs_started_at'), 'sync_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_sync_runs_user_id'), 'sync_runs', ['user_id'], unique=False)
    op.create_index('ix_sync_runs_user_started', 'sync_runs', ['user_id', 'started_at'], unique=False)
    op.create_table('workspace_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notion_integration_id', sa.UUID(), nullable=False),
    sa.Column('root_page_id', sa.Text(), nullable=True),
    sa.Column('template_version', sa.Text(), nullable=True),
    sa.Column('discovered_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovery_status', sa.Text(), nullable=True),
    sa.Column('discovery_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notion_integration_id'], ['notion_integrations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_configs_notion_integration_id'), 'workspace_configs', ['notion_integration_id'], unique=True)
    op.create_index(op.f('ix_workspace_configs_user_id'), 'workspace_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_configs_user_id'), table_name='workspace_configs')
    op.drop_index(op.f('ix_workspace_configs_notion_integration_id'), table_name='workspace_configs')
    op.drop_table('workspace_configs')
    op.drop_index('ix_sync_runs_user_started', table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_user_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_started_at'), table_name='sync_runs')
    op.drop_index('ix_sync_runs_failed_pending', table_name='sync_runs', postgresql_where="status IN ('failed', 'pending')")
    op.drop_index(op.f('ix_sync_runs_external_integration_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_notion_integrations_workspace_id'), table_name='notion_integrations')
    op.drop_index(op.f('ix_notion_integrations_user_id'), table_name='notion_integrations')
    op.drop_table('notion_integrations')
    op.drop_index(op.f('ix_external_integrations_user_id'), table_name='external_integrations')
    op.drop_table('external_integrations')
    op.drop_table('users')
    # ### end Alembic commands ###
